### ISSUE TITLE
browser is not defined when running with protractor 0.13 + 

### ISSUE THREAD

**Issue by facultymatt** [aeh/grunt-mocha-protractor#7]
getting the following error: `browser is not defined` when running tests. Looks like the module doesn't yet utilize the globally exposed `browser`, `by` and other changes (and no longer the need for `var ptor = this.ptor;`) that was recently introduced.

**Comment by facultymatt** [comment]
Looking into this further, it seems that using `ptor = protractor.wrapDriver(driver);` requires writing your tests using a slightly modified syntax. For example you'd need to write 

```
ptor.findElement(protractor.By.id('page1')).click();
```

instead of the shorthand version available when not using the `wrapDriver` method

```
ptor = protractor.wrapDriver(driver);
```

This was not such a big deal prior to version `0.12.0`, where `var ptor = this.ptor;` was common place, and the `by`, `browser`, etc. methods were not exposed. Now its a bit of a hinderance. At the very least we should make a note in the readme... ideally though things would be more seamless.

**Comment by aeh** [comment]
This isn't so much a failing of using `protractor.wrapDriver(driver)` as it is the fact we aren't using the built in jasmine test harness.  All those global variables are added in the `runJasmineTests` in the protractor runner.

So that we have access to those globals as well I have copied them into our runner as well (as of version 0.4.0).  Note that if protractor adds more or changes these we will need to come back and update this as well.
